### ISSUE TITLE
List on Kong Hub and then announce on Kong Nation

### ISSUE THREAD

**Issue by coopr** [phpdocker-io/kong-certbot-agent#11]
This is a great contribution to the Kong community - thanks!

I invite you to add this to Kong Hub https://docs.konghq.com/hub/ - see https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#contributing-to-kong-documentation-and-the-kong-hub for details.

Once added, it'd be great if you'd like to announce it on Kong Nation https://discuss.konghq.com/c/announcements

**Comment by luispabon** [comment]
Hi @coopr, I'll be working on this project over the weekend, I'll make sure to do so 👍

**Comment by judithpatudith** [comment]
@luispabon Thanks for creating this! We're looking for community members to demo their projects on the [Kong community call](http://bit.ly/2QlIh5H). The next one will happen on November 13th at 10am Pacific time. Are you interested in presenting this project? 

We're trying to prioritize projects that are listed in the Hub, but we can definitely slate you on the agenda as long as the PR to the Hub gets merged before the call. Let me know if you're interested; I'd love to hear from you!

**Comment by luispabon** [comment]
@judithpatudith apologies for the late response as I've been away on holidays. I'm afraid work will keep me very busy around those dates, otherwise I'd love to parcitipate.

**Comment by judithpatudith** [comment]
No problem at all. We have a call every month: might you be interested in the December (date TBD) or the January 8th call?

**Comment by judithpatudith** [comment]
Hi @luispabon I know its short notice, but if you're available we have an open spot this coming Tuesday (Dec 4th) at 10 am Paicific. The demo can be very informal so no need for too much preparation 🙂 

If not, January 8th is also still open
