### ISSUE TITLE
question: auto grab snis

### ISSUE THREAD

**Issue by lukasa1993** [phpdocker-io/kong-certbot-agent#42]
since we specify kong admin wont it be great to make domains argument optional and grab domains from kong admin snis?

**Comment by luispabon** [comment]
There's a very real danger for setups that mix Let's Encrypt certs with certs from other sources to break SSL when trying to be too clever. It is much safer to be explicit in your configuration.

Also, when you provide a list of domains for LE to issue a cert with, the single cert generated is valid for all those domains, which lowers load at Let's Encrypt's end. Remember, LE is a shared resource and we need to be mindful of that.
