### ISSUE TITLE
cron-Command not found

### ISSUE THREAD

**Issue by mkalus** [phpdocker-io/kong-certbot-agent#45]
I just downloaded and started the latest Docker file from the hub and get the following error:

./entrypoint.sh: line 7: cron: command not found

It seems that the phpdockerio/php73-cli base image is missing cron. The Dockerfile should install cron Package to solve this.

**Comment by luispabon** [comment]
Good catch. The instructions do say you need to specify the cmd to run when using the container:

```
docker run -it --rm phpdockerio/kong-certbot-agent \
    ./certbot-agent certs:update \
    http://kong-admin:8001 \
    foo@bar.com \
    bar.com,foo.bar.com,www.bar.com
```

That missing script is an oversight from an older version. I'll fix soon.
